### ISSUE TITLE
Consider recommending dcm2bids for data processing / preparation

### ISSUE THREAD

**Issue by surchs** [neurobagel/documentation#100]
Based on our experience with BIDSification by @danyluik at the Douglas it seems that [dcm2bids](https://github.com/UNFmontreal/Dcm2Bids) is a bit easier to follow than heudiconv  - both in terms of docs and process for someone new to both processes. 

We should

- [ ] point to [dcm2bids](https://github.com/UNFmontreal/Dcm2Bids) in our docs when we talk about BIDSification
- [ ] discuss if we want to start recommending / providing guides for dcm2bids over heudiconv

Maybe @danyluik you can pitch in and mention what your experience has been like with these tools.
Any thoughts @michellewang and @nikhil153 ?

**Comment by danyluik** [comment]
For sure:

On the heudiconv front, I found I had to bounce through a bunch of different tutorials to get it working. Tutorials generally only had instructions for Docker vs. Singularity. Also a bit clunky if you're tinkering with your heuristic and testing as you go: it creates a hidden .heudiconv folder for each subject/session that stores info on your past conversions, which it'll default to if you don't explicitly delete it before running a new conversion (a bit annoying on one hand, and something someone could potentially miss on another - I definitely did until I figured it out :) ) 

dcm2bids - super straightforward, the main docs page was easy to follow. Would also echo that it's super beginner friendly (i.e., starts all the way back at making a conda environment). If you're pointing any given user to a converter, I'd definitely recommend it.

**Comment by alyssadai** [comment]
Hey @neurobagel/dev, should we close or rename this issue for now? Now that the Nipoppy docs live on their own website, I'm wondering if  BIDS conversion is something we still need to discuss in detail on our docs as this recommendation issue suggests. Our CLI does require BIDS data, but we could either just provide some tool links directly in a tip admonition, or leave the user to handle that on their own.

Alternatively, it looks like there's already a Nipoppy page on converting datasets to BIDS: https://nipoppy.readthedocs.io/en/latest/user_guide/bids_conversion.html

We could consider directing users to this link for more info as well.

**Comment by surchs** [comment]
Agreed, I think this is addressed over in nipoppy land. Let's close
