### ISSUE TITLE
Describe how to upload vocabulary (`.ttl`) files

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/documentation#104]
We now have a vocabulary file located in https://github.com/neurobagel/api/blob/0b44bcd6a156bb3826c76baf519be335a756b2f9/vocab/nb_vocab.ttl

We need to explain how users should add this to a freshly created graph.

Steps:
- [x] Document / Explain what the point / purpose of the vocabulary files is
- [x] Document where to obtain the Neurobagel vocabulary `.ttl` file (i.e., the `vocab/` subdirectory of the API repo)
- [x] Document how to use `add_data_to_graph.sh` to upload the new `.ttl` file to a new graph DB
  - [x] Recommend that users either
      - ~**A.** store a copy of `nb_vocab.ttl` in the same folder that their dataset JSONLDs are stored (to make updating the data in the graph easier / one step)~
      OR
      - **B.** remember to always run `add_data_to_graph.sh` on both their directory containing dataset JSONLDs **and** then separately on the `vocab/` directory containing vocab `.ttl` files

**Comment by surchs** [comment]
@alyssadai anything to add or does this look good?

**Comment by alyssadai** [comment]
Hey @surchs, this looks pretty good. I added a subtask for the recommendation of where to store the `nb_vocab.ttl` file for easiest graph data updating (i.e., should it always be uploaded from the original `vocab/` directory or from a dedicated graph data directory?)

Could you look at the last checkbox and let me know if **A** or **B** sounds better to you? (Or, I guess, we could explicitly give users the option to do one or the other)

**Comment by surchs** [comment]
let's go with B
