### ISSUE TITLE
[ENHANCEMENT] Provide a sensible way to generate a password for the DBUser

### ISSUE THREAD

**Issue by gdevenyi** [neurobagel/documentation#109]
`openssl rand -hex 16`

- [x] Add a note on using a secure password
- [x] Add a note that passwords in the `.env` file are now handled as docker secrets (unlike most other variables in the .env file)
- [x] Add the suggestion from Gabe for how to create a safe password.

**Comment by surchs** [comment]
Hey @gdevenyi, thanks for the suggestion. I think that would be nice to have but it's not a focus right now. If you have resources to suggest / contribute, we'd happily merge them

**Comment by surchs** [comment]
I think this best fits at the end of this section: https://neurobagel.org/config/#environment-variables
