### ISSUE TITLE
Change default graph to graphDB

### ISSUE THREAD

**Issue by surchs** [neurobagel/documentation#131]
When a new user goes to our docs they should

- [x] #150
- [x] see all configurations rewritten for graphDB with notes for stardog as "exceptions"
- [x] #153
- [ ] no longer see references to stardog in images or icons

We should also discuss removing Stardog entirely.

edit: now that we no longer have a standalone Stardog license and it is very unlikely that anybody else would get one either, we should entirely remove the Stardog docs!

**Comment by alyssadai** [comment]
Closing since we have not fully deprecated Stardog. Will cross the bridge when we get there.
