### ISSUE TITLE
Switch local node setup instructions to use `recipes` repo

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/documentation#144]
### Description

Local node setup instructions should be updated to use config files from the newly created https://github.com/neurobagel/recipes instead of repo-specific files.

TODO:
- [x] https://neurobagel.org/infrastructure/#clone-the-api-repo should instead point to recipes

**Comment by alyssadai** [comment]
Related to https://github.com/neurobagel/recipes/issues/9

**Comment by surchs** [comment]
@alyssadai I think we already have this for the local federation, no: https://neurobagel.org/federate/#configuration-files or is there something else to be done for that? If not, let's rename issue to -> "switch node deployment to use recipes" or something similar

**Comment by alyssadai** [comment]
You're right! It's only the node setup page that needs to be updated.

Issue description has been updated.
