### ISSUE TITLE
Query tool standalone version code snippet did not work

### ISSUE THREAD

**Issue by barbarastrasser** [neurobagel/documentation#179]
### Description

As in the end it worked out, it might be a documentation issue more than an issue of the query tool itself.

The command
`docker run -d -p 3000:3000 --env API_QUERY_URL=http://localhost:8000/ --name query_tool neurobagel/query_tool:latest`

did not work out – I couln’t start the query tool container (I always used the default port mappings). 

![NiDkbZ](https://github.com/neurobagel/documentation/assets/162976974/c1f48968-a9ba-4e0f-9244-36199e147681)

After changing the `API_QUERY_URL` to `NB_API_QUERY_URL` I could start it and inspect the `app/vite.config.ts` where I figured out that the returned port is `5173`.

After some trial and error the command:
`docker run -d -p 3000:5173 --env NB_API_QUERY_URL=http://localhost:8000/ --name query_tool neurobagel/query_tool:latest`  

got me to what I would see as desired result:
![image](https://github.com/neurobagel/documentation/assets/162976974/5b116bcf-99e5-4789-bc51-b340d4c1a972)

Is this then the right command or did I do something wrong and it worked out accidentally?

### Relevant documentation pages

https://neurobagel.org/infrastructure/#deploy-a-graphical-query-tool

**Comment by alyssadai** [comment]
Connecting @rmanaem as I think he can explain what's happening here a bit better :)

In short, I think this is a documentation issue.

**Comment by rmanaem** [comment]
Hi @barbarastrasser
Thanks for bringing this to our attention. We recently refactored the tool and it seems updating the docs slipped my attention.
In the meantime, you can find the most up-to-date version of the docs on [query tool's README.md](https://github.com/neurobagel/query-tool?tab=readme-ov-file#query-tool).

**Comment by alyssadai** [comment]
Thanks @rmanaem. To clarify, we also need to update our deployment [recipes](https://github.com/neurobagel/recipes) as the docker-compose.yml files and others also have this variable baked in.

So, the steps to fix this are:
- [ ] Update all references to `API_QUERY_URL` in the documentation, which includes:
  - [ ] https://neurobagel.org/infrastructure/
  - [ ] https://neurobagel.org/federate/
  - [ ] https://neurobagel.org/query_tool/ (if you want @rmanaem, we can sync this page with the query tool README)
- [ ] https://github.com/neurobagel/recipes/issues/25
