### ISSUE TITLE
Link to adding new data

### ISSUE THREAD

**Issue by seanhatton** [neurobagel/documentation#197]
### Description

In the https://neurobagel.org/getting_started/ at the bottom is a link "[Add your own data to your Neurobagel graph](https://neurobagel.org/maintaining/#updating-the-data-in-your-graph) to search". The better link to the adding data looks like it should be https://neurobagel.org/config/#uploading-data-to-the-graph-store.

**Comment by alyssadai** [comment]
Closed by https://github.com/neurobagel/documentation/pull/198.

n.b.: https://neurobagel.org/config/#uploading-data-to-the-graph-store is not actually the recommended instructions for updating data in an already set-up graph - these explain the _manual_ commands that you would use to upload data, but these are already automated by the setup script provided in [neurobagel/recipes](https://github.com/neurobagel/recipes).

**Comment by alyssadai** [comment]
Closed by https://github.com/neurobagel/documentation/pull/198.

n.b.: https://neurobagel.org/config/#uploading-data-to-the-graph-store is not actually the recommended instructions for updating data in an already set-up graph - these explain the manual commands that you would use to upload data, but these are already automated by the setup script provided in [neurobagel/recipes](https://github.com/neurobagel/recipes).
