### ISSUE TITLE
Confusion about users

### ISSUE THREAD

**Issue by gdevenyi** [neurobagel/documentation#20]
The documentation regarding the users created during the installation process is confusion in terms of naming.

This is partially due to this https://github.com/neurobagel/api/issues/121 where API could mean two different things.

In addition, both admin and superuser are used to describe the same user.

Suggest a more coherent naming scheme.

1. Database Admin -- this is the `admin` stardog creates, which needs its password changed
2.  Database user -- this is the user the backend API server will use to talk to the database

"API User" reads to me as a user with permission to access the API, a feature not implemented in the API server, so I suggest adjusting the naming schemes.

See also https://github.com/neurobagel/api/issues/119

**Comment by gdevenyi** [comment]
I hate stale bots on githib with a passion.

**Comment by Remi-Gau** [comment]
I agree though I think in this case I think the team would like to call it a "forget me not bot". 😉

**Comment by surchs** [comment]
yeah, we need bots to automatically flag stuff that needs attention across repos. We will probably make the bot ignore certain issues that we don't have any plans of addressing soon - so there will be fewer of these labels. I made an issue for this https://github.com/neurobagel/workflows/issues/3, happy to get your input on it
