### ISSUE TITLE
Extend and simplify "getting started"

### ISSUE THREAD

**Issue by barbarastrasser** [neurobagel/documentation#205]
### Description

In general, the narrative style of the documentation and the background information that is included has a high educational value and reads great! Since there is a lot of information in it, it might be hard for the user to immediately  find the needed command for any step.

By now the "getting started" documentation leads to a setup of the the services, but does not contain how to add data to the graphDB and consecutive steps. An extension to a complete "Quick Start" section might be helpful to the user.

If someone runs into problems or wants additional information, the extensive docs can be linked. 

### Relevant documentation pages

https://neurobagel.org/getting_started/

### Additional details

My idea would be to give a complete (from setup of the services to querying the data), but very concise "Quick Start" instruction without any additional information like 

- Setup of services 
`command A`
`command B`
- Prepare data
`command A`
`command B`
- Add data
` command A`

etc..

**Comment by surchs** [comment]
Thanks @barbarastrasser for the issue! I think we missed this issue during the docs refactor. Would you mind taking a look at the current docs to see if your point is resolved?

**Comment by barbarastrasser** [comment]
> Thanks [@barbarastrasser](https://github.com/barbarastrasser) for the issue! I think we missed this issue during the docs refactor. Would you mind taking a look at the current docs to see if your point is resolved?

Yes, I think it's resolved. What I find now, is a complete setup from beginning to end. Also, I find all the links to more detailed descriptions 👍  🥳

**Comment by surchs** [comment]
Excellent, and thanks again!
