### ISSUE TITLE
Deprecate or remove Nipoppy docs in favour of readthedocs?

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/documentation#218]
The idea here would be to keep the link but

- [x] remove the dedicated "Preparing data using Nipoppy" tab
- [ ] add an explanation to what Nipoppy is and how it fits with Neurobagel
- [x] add a link to Nipoppy into the User guide, probably in the "Preparing your data" section with a hint that we expect data to look like Nipoppy says. 
- [ ] Maybe an extra example in this section for very basic use cases that may not want / need to go through the Nipoppy setup

**Comment by michellewang** [comment]
The Nipoppy Readthedocs are still missing a page for the tabular data, so right now the only thing we have in the docs that is relevant to Neurobagel would be the DICOM reorg and BIDSification parts, and in that case what Neurobagel expects the data to look like would be just BIDS

**Comment by surchs** [comment]
There are a couple of nipoppy links that now don't work anymore, see https://github.com/neurobagel/documentation/actions/runs/10816495878/job/30007788750?pr=223

@michellewang do you maybe have refactored the nipoppy repo recently?

**Comment by michellewang** [comment]
@surchs yes, the old Nipoppy docs on the Neurobagel website are obsolete. Pretty sure we can remove them now unless @nikhil153 says otherwise

**Comment by alyssadai** [comment]
Hey @surchs and @michellewang, since the old Nipoppy section is breaking checks in our docs right now, I would suggest we just address this issue by 

1. Removing the "Preparing data with Nipoppy" section 
2. Sticking a really short & simple admonition in the https://neurobagel.org/data_prep/ page for now, with something like:

> Looking for broader/more general guidance on organizing the imaging and tabular data for your dataset?
>
> We recommend also checking out [Nipoppy](link to docs), a protocol for standardized organization and processing of clinical-neuroimaging datasets that extends BIDS. Neurobagel tools are designed to be compatible with data organized according to the Nipoppy specification, although you do not necessarily need to use Nipoppy to use Neurobagel.

We can add more details in the future once there are more concrete links between Nipoppy outputs & Neurobagel, but I think for now this is sufficient

wdyt?

**Comment by michellewang** [comment]
Sounds good to me!
