### ISSUE TITLE
Add link to Neurobagel Discord server

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/documentation#220]
### Description

Provide link to our Discord server?

### Relevant documentation pages

https://neurobagel.org/getting_help/

**Comment by alyssadai** [comment]
@Remi-Gau, have you experienced any issues with openly sharing a permanent Discord invite link to any of the servers you help manage? Wondering if there's easy extra steps we can take to prevent bots/bad actors from overloading the server (maybe).

**Comment by Remi-Gau** [comment]
Don't have much experience. Maybe some of the team involved in the ohbm brainhack may know.
