### ISSUE TITLE
Certificate error 

### ISSUE THREAD

**Issue by alexpron** [neurobagel/documentation#221]
### Description

I have an invalid certificate error when trying to access the neurobagel website see image below
![image](https://github.com/user-attachments/assets/2d74a583-52c4-456e-9eee-9377c52f6807)

**Comment by surchs** [comment]
Thanks @alexpron for the report! I believe this is an issue we've seen before where cloudflare's DNS proxy is preventing GH pages from renewing the SSL certificate for our domain. We can do our short-term fix of disabling proxy, and then we should have a real fix this time.

Also tracked here: https://status.neurobagel.org/incident/63

**Comment by surchs** [comment]
OK, the core issue is resolved again. I'd say we keep this issue open though to discuss a long-term solution. Ideally we'd want to not have to manually fix this next time

**Comment by surchs** [comment]
Without reading deeply, this appears to discuss the issue: https://gist.github.com/zbeekman/ac6eeb41ea7980f410959b13416d74c9

**Comment by alyssadai** [comment]
Closing as the website is accessible again and we have a temporary manual workaround for this issue. Will investigate a more automatic solution for certificate renewal in https://github.com/neurobagel/planning/issues/165.
