### ISSUE TITLE
Datalad link missing

### ISSUE THREAD

**Issue by seanhatton** [neurobagel/documentation#231]
### Description

"Downloading of imaging data is performed via [datalad](https://rpq-qpn.ca/en/home/). " Links to QPN, not datalad instructions. Should this link to Datalad/OpenNeuro instructions.

### Relevant documentation pages

https://neurobagel.org/public_nodes/

**Comment by alyssadai** [comment]
Thanks for bringing this to our attention @seanhatton! This will be fixed as part of https://github.com/neurobagel/documentation/pull/233.
