### ISSUE TITLE
Add example JSONLD with derivatives metadata to examples list

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/documentation#238]
### Description

Current examples only include valid JSONLDs with phenotypic and BIDS data.

### Relevant documentation pages

https://neurobagel.org/graph_data/#example-jsonld-files

### Additional details
Here's the JSONLD with derivatives: https://github.com/neurobagel/neurobagel_examples/tree/main/data-upload/pheno-bids-derivatives-output

_No response_

## TODO

- [ ] link existing .jsonld file in the docs

**Comment by surchs** [comment]
Should this be in neurobagel/examples instead?
