### ISSUE TITLE
Add example docker-compose.yml variation with NGINX+ACME

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/documentation#239]
### Description

Should contain our current [docker compose recipe](https://github.com/neurobagel/recipes/blob/main/docker-compose.yml) as well as the containers from https://github.com/neurobagel/internal_deployment/blob/main/docker_nginx.yml.

Include instructions on environment variables that need updating, via annotations.

**Comment by surchs** [comment]
The idea would be for a user to copy/paste the entire file as a replacement for the docker-compose.yml in the recipes repo, and, assuming they have followed the other setup steps, should just be able to run docker compose up
