### ISSUE TITLE
Add examples of values for each age heuristic

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/documentation#26]
Can create a separate column in the table in this section: https://www.neurobagel.org/documentation/dictionaries/#age

**Comment by Remi-Gau** [comment]
Quick suggestion while I see this one.

Have an actual TSV in the doc repo with columns for each neurobagel defined "type" and render it directly in the doc with the markdown-include extension.

https://github.com/cmacmackin/markdown-include

Allows you use this file for testing other tools.
