### ISSUE TITLE
keep an actual output (csv files) of the query tools accessible for downstream tools to use as input

### ISSUE THREAD

**Issue by Remi-Gau** [neurobagel/documentation#27]
Currently the examples of the output lives in the wiki here:
https://github.com/neurobagel/documentation/wiki/Query-Tool#example-data

So I am having to "mock" an output here if I want to run tests on this "cohort creator" script:
- https://github.com/neurodatascience/cohort_creator/blob/main/inputs/datasets.tsv
- https://github.com/neurodatascience/cohort_creator/blob/main/inputs/participants.tsv

What would be useful would be to keep actual csv or tsv files the downloads of the query gives, so they can be more easily ingested by downstream tools for testing.

Obviously this could also be used for the testing of the query tools itself to ensure it gives the correct output files.

### Steps to implement:
- [x] add section to https://neurobagel.org/query_tool/ containing contents of https://github.com/neurobagel/documentation/wiki/Query-Tool#example-data
- [x] replace markdown tables with a link to example results TSVs from `neurobagel/neurobagel_examples` or render the examples directly on the docs

**Comment by alyssadai** [comment]
Related to https://github.com/neurobagel/query-tool/issues/152

**Comment by alyssadai** [comment]
To further spec this issue, I think @rmanaem that we could just move the current internal wiki page about the query tool outputs to the public facing https://neurobagel.org docs entirely. Maybe in a section called "Outputs" on this page https://neurobagel.org/query_tool/?

**Comment by surchs** [comment]
blocked by https://github.com/neurobagel/query-tool/issues/152

**Comment by surchs** [comment]
Not blocked anymore, ready to be worked on
