### ISSUE TITLE
Add link to reference phenotypic data dictionary with all possible cases of missing values

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/documentation#28]
On "Data dictionaries" page:
- [x] Link to https://github.com/neurobagel/bagel-cli/blob/main/bagel/tests/data/example_synthetic.json
- [x] Add new "Missing values" section that briefly describes which vars can have missing values

**Comment by surchs** [comment]
Hey, since this was split off from https://github.com/neurobagel/bagel-cli/issues/144 during specification, I think it should go directly into specify-done (after a quick look at the specification). @alyssadai could you take a look and then move it unless you disagree?

**Comment by alyssadai** [comment]
Blocked by availability/new prioritization.
