### ISSUE TITLE
Add documentation on setting up Node 'tasks' for Cypress

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/documentation#29]
This Cypress ability was something we first utilized for the annotation tool in https://github.com/neurobagel/annotation_tool/pull/433

See here for examples:

[How do I list the contents of the download directory in Cypress? I need to make sure that there are files of unknown name parts in there](https://stackoverflow.com/questions/73971115/how-do-i-list-the-contents-of-the-download-directory-in-cypress-i-need-to-make)](https://stackoverflow.com/questions/73971115/how-do-i-list-the-contents-of-the-download-directory-in-cypress-i-need-to-make)

[Cypress documentation on cy.task](https://docs.cypress.io/api/commands/task)

**Comment by jarmoza** [comment]
Documentation link: https://github.com/neurobagel/documentation/wiki/Cypress-Tasks

**Comment by rmanaem** [comment]
Nicely done Jonathan, I just have one comment and that is to specify the language of markdown code blocks.

**Comment by jarmoza** [comment]
Take a look now @rmanaem.

**Comment by rmanaem** [comment]
🧑‍🍳
