### ISSUE TITLE
Add info on requirements for the phenotypic .tsv

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/documentation#35]
Currently, the index / "Welcome" page contains some info about preparing tabular data for Neurobagel tools. We should move this to a dedicated page on data prep (see also #40), and describe the minimum data needed to use the annotation tool and CLI, i.e. a properly formed phenotypic .tsv, and what the .tsv needs to contain.

- Should match constraints imposed by annotation tool (see "Next page criteria" in README section https://github.com/neurobagel/annotation_tool/blob/master/README.md#categorizing-data-table-columns)

### Current constraints
- [x] File needs to be tab-separated, a .tsv
- [x] Each row of tsv should correspond to a single subject session
- [x] At least 2 columns must be present: one containing subject identifiers (in Neurobagel world, a column annotated as `isAbout: nb:ParticipantID`), and _one other column_ containing info about demographics or assessment tools (currently, Neurobagel can handle sex, age, diagnosis/group, and/or cognitive assessment columns)
  - [x] If the dataset has a corresponding BIDS directory (i.e., raw imaging data), at least one column in the tsv must contain subject identifiers that are the same as the names of BIDS subject subdirectories
    - [x] Currently, we also expect that the subject IDs in the phenotypic.tsv are a superset of the subject IDs in the BIDS directory - that is, a subject cannot exist who has a BIDS directory but doesn't have a corresponding row in the phenotypic .tsv

**Comment by jarmoza** [comment]
@alyssadai To be clear, all of the current requirements for the annotation tool to go from phenotypic tsv and optional data dictionary are included in the [new annotation tool readme](https://github.com/neurobagel/annotation_tool/blob/master/README.md). They are currently separated out by page under the heading 'Next Page Criteria'.

**Comment by alyssadai** [comment]
Yep! Noted 🙂 I'm envisioning that this page will be more a one-stop "before you start" list for folks needing to generate TSVs that can go through the whole data upload workflow without issue (like `mr_proc` folks, who've requested a wiki page with a list of requirements). The annotation tool README is definitely still helpful for folks who are imminently using the annotation tool, but hopefully this wiki page will save a bit of time scrolling as well.

Currently, there are also some details pertaining to the .tsv that are important for the CLI but not necessarily the annotation tool, i.e. that the subject IDs for BIDS data must be subset of those present in the phenotypic .tsv. This would be a good place to note those!
