### ISSUE TITLE
Setup auto-deploy on push

### ISSUE THREAD

**Issue by surchs** [neurobagel/documentation#38]
We're currently still suggesting that contributors should push from their local repo using the [`mkdocs gh-deploy` routine](https://www.mkdocs.org/user-guide/deploying-your-docs/). That's annoying and inconsistent, and can probably break real quick. We should instead setup an automatic deployment.

One option is to just use Netlify, now that we have https://github.com/neurobagel/project/issues/135

**Comment by rmanaem** [comment]
Closing this since there already is an auto-deploy action set up. See [cd.yaml](https://github.com/neurobagel/documentation/blob/main/.github/workflows/cd.yaml).
