### ISSUE TITLE
[ENH] Update docs: tools section, about us, & more

### ISSUE THREAD

**Issue by surchs** [neurobagel/documentation#40]
Have a new section about our tools which has a page each for the annotation tool, CLI, infrastructure/graph, and query tool.

All pages except "Infrastructure" will be initialized as the README of the respective tools. Infrastructure will be reused from the current "Getting started" section.

Revised docs structure (`nav`) w/ proposed additions:
  - [x] Welcome: "index.md"
    - Mission statement + getting help
  - [x] Getting started: "start.md"
    - [x] Ecosystem overview
    - [x] Describe basic use cases and link to the relevant tool pages under "User guide"
  - [x] User guide:
    - [x] Preparing data: "data_prep.md"
      - Contents currently in "Welcome" page
    - [x] Annotating a dataset: "annotation_tool.md"
    - [x] Generating harmonized subject-level metadata: "cli.md"
    - [x] Setting up a graph: "infrastructure.md"
      - Contents currently in "Getting started" page (i.e., deployment instructions)
    - [x] Using the API
    - [x] Running cohort queries: "query_tool.md"
  - [x] data models section
  - <mr_proc section>
  - [x] About us: "about.md"
    - Team + funders
  - [x] How to cite

**Comment by alyssadai** [comment]
I think this sounds good!

One suggestion - I still like the idea of having a "Getting started" page so a first-time user knows what to look at first.

Since we will have this new tools section and tool pages, how about keeping the "Getting started" section but simplifying it to point to different tool pages depending on the use case?

Something like:

> If you would like to annotate an existing dataset using Neurobagel, see "Annotation".
> If you want to search for participants based on specific criteria, see "Query".
> If you want to deploy our tool stack at your local research institute, see "Infrastructure"

**Comment by surchs** [comment]
Good idea and agree about the need to have such a section. We can continue expanding on your suggestion in the future. One thought I'm getting: we have 

- the current issue (i.e. add a "Tools" section)
- your point about adding / keeping a changed "Getting started" section
- https://github.com/neurobagel/documentation/issues/32, i.e. Make a new section for "Data Models" (or "Schemas") and put "Data Dictionaries", and "Graph data model" inside this section
- an "About" section (that could also go on a separate website) to include:
  - brief mission statement
  - face / name / link / brief bio of contributors
  - roadmap link / high level
- MR_proc, which could be renamed to: -> Prepare data with MR_proc

Except for the (optional) "About" section, these are all about moving content around, and not (less) about creating content. How about we do this all in one go?

**Comment by alyssadai** [comment]
Sure, I can take a stab at this, and 'promote' importance of https://github.com/neurobagel/documentation/issues/32 on the board again.

For https://github.com/neurobagel/documentation/issues/32, my plan for the page for the graph-ready data is to include a new brief description of the JSONLD and a link to our comprehensive reference example .jsonld for now (the existing "Data models" page also actually talks about the data dictionary schema, so I'll probably move that under the page for the data dictionary).
