### ISSUE TITLE
Add (internal) docs for graphDB deployment steps

### ISSUE THREAD

**Issue by surchs** [neurobagel/documentation#58]
While our offical docs still instruct for Stardog as the RDF backend, we'll move away from it as soon as we have evaluated the alternatives. In the meantime our most explored option is graphDB. Because other sites want to experiment with our tools without having to go through the prohibitively complicated license process for Stardog we need to provide some instructions for graphDB now. 

We need:
- [x] a page on our internal wiki for configuration of graphDB
- [x] explain what needs to be adjusted in the `.env` files to make it run with graphDB
- [x] highlight the commands for first-setup operations for graphDB:
  - [x] make user
  - [x] make graph
  - [x] set password
- [x] ~~make suggestions for how to re-upload a bunch of .jsonld files (e.g. keep them around in one place)~~ will reuse https://github.com/neurobagel/documentation/issues/52 when it is done.

take commands from here: https://github.com/neurobagel/api/pull/141

**Comment by surchs** [comment]
Output of this is here: https://github.com/neurobagel/documentation/wiki/Alternative-Graph-Backend-deployment

**Comment by surchs** [comment]
Thomas already tried the docs in their current form. See feedback here: https://github.com/neurobagel/documentation/issues/67

**Comment by surchs** [comment]
We might want to explain how to get rid of data in the graph as well (e.g. I have uploaded bad data).

graphDB: https://rdf4j.org/documentation/reference/rest-api/#tag/Repositories/paths/~1repositories~1%7BrepositoryID%7D~1statements/delete

**Comment by alyssadai** [comment]
Closing on behalf of @surchs as I have successfully tested the steps out locally and also helped Thomas to troubleshoot some issues encountered during the deployment process.

As part of this review I fixed some code typos in the wiki page as well as updated the section for adding test data to use the new `add_data_to_graph.sh` script (https://github.com/neurobagel/api/pull/156) as well as data from our neurobagel_examples repo.

The changes can be viewed in this diff: https://github.com/neurobagel/documentation/wiki/Alternative-Graph-Backend-deployment/_compare/a38c6a03567296a76241d722a05823bb78ff39a5...241a4c4640b9ada386d7bfae4fdb77c9d25915fe
