### ISSUE TITLE
Split instructions for running containerized CLI into Singularity and Docker

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/documentation#60]
- [x] add explicit command examples for Singularity
  - [x] try out [mkdocs content tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#linked-content-tabs) to separate Singularity / Docker commands
- [x] add general warning that `bids` command is very slow
- [x] fix example Docker run command to use official Docker Hub image
- [x] add section describing input data needed for CLI

**Comment by surchs** [comment]
could make sense to also handle this via tabs, as a test case for https://github.com/neurobagel/documentation/issues/74

**Comment by alyssadai** [comment]
oh, that's a good idea @surchs. I'll try that
