### ISSUE TITLE
feedback for inserting test data into the graph

### ISSUE THREAD

**Issue by thomasbeaudry** [neurobagel/documentation#70]
In the "Upload test data to the graph" section, the command:

curl -i -X POST http://localhost:7200/repositories/<graph-name>/rdf-graphs/default -H "Content-Type: application/ld+json" --data-binary "@./ds001618.jsonld

is missing the -u flag, it should be:

curl -i -X POST http://localhost:7200/repositories/dnp/rdf-graphs/default -H "Content-Type: application/ld+json" --data-binary "@./ds001618.jsonld" -u "admin:yourpassword"
HTTP/1.1 100 

I also suggest, that you include the expected result of the command, so the sysadmin knows that it executed correctly, i.e:

HTTP/1.1 204 
Vary: Accept-Encoding
Cache-Control: no-store
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Content-Language: en-US
Date: Wed, 06 Sep 2023 15:33:49 GMT
Server: GraphDB/10.3.1 RDF4J/4.3.5

I would also add a few test files to the install zip / repo, so the sysadmin can test those files instead of tracking them down from another source.

**Comment by alyssadai** [comment]
Thanks for the feedback @thomasbeaudry!

These suggestions should be addressed in the updated ["Upload test data to the graph"](https://github.com/neurobagel/documentation/wiki/Alternative-Graph-Backend-deployment#upload-test-data-to-the-graph) section of the graphDB wiki page. The new script used to upload data (add_data_to_graph.sh) also outputs a completion message when the upload is finished.

Feel free to add to this thread if you have further feedback on the updated instructions!

**Comment by surchs** [comment]
Thanks @alyssadai, I agree that the original issue is addressed by the script you added. That said, as long as we still expect users to push data to the graph via curl or script, we should also list these commands explicitly in the docs - users may have different plans for how to use these instructions.

So I think: 
- updated command to push data
- command to clear out data
- your existing section on "we have a script for you that does both"

Would make sense. With that, I think we can close this issue.

**Comment by alyssadai** [comment]
Wiki page updated @surchs
