### ISSUE TITLE
Handle docs for both graphDB and Stardog via tabs on the public docs

### ISSUE THREAD

**Issue by surchs** [neurobagel/documentation#74]
Because of their restrictive licensing policy, we are currently transitioning away from Stardog as our backend but haven't settled on a default replacement: https://github.com/neurobagel/planning/issues/9

In the meantime we suggest people use graphDB as the graph backend. We therefore started maintaining two different sysadmin setup instructions, one for Stardog and one for graphDB as backends. Not fun, but necessary. We also maintain these two sets of instructions in two different places: Stardog on the public docs, graphDB in the internal docs. That's bad and confusing (see e.g. here: https://github.com/neurobagel/documentation/issues/67).

Let's 
- keep both backend instructions in the public docs by merging the graphDB docs into the public docs
- let users switch between their desired backend using the [linked tabs feature](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#linked-content-tabs)
- give some context for why there are two backends and how to pick
- not write any new docs, but just refactor the existing docs

Also, we should make the code syntax highlighting consistent across this docs page.

This should hopefully make it easier for us to make clear what aspects of the setup instructions are shared between the two backends, and which aspects are unique and different.

**Comment by surchs** [comment]
Because we now render a .tsv table from the api in the docs: https://github.com/neurobagel/api/blob/main/docs/api_environment_variables.tsv, we'll have to go back later and update this table as well. And we may have to create two flavours of this table, one for each graph deployment

**Comment by alyssadai** [comment]
@surchs just a heads up that I noticed a typo in the existing instructions for Stardog, and have opened an issue here https://github.com/neurobagel/documentation/issues/93.

I'll leave it up to you if you want to address it as part of this PR, since you're updating that same page 🙂
