### ISSUE TITLE
Update nipoppy docs

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/documentation#85]
The nipoppy section of the docs need to be update as the [`mriqc.md` file](https://neurobagel.org/nipoppy/workflow/proc_pipe/mriqc/#mriqc) contains a dead link to `DOCKERFILE` that no longer exists:

> Ensure you are running the appropriate MRIQC image, as provided [here](https://github.com/neurodatascience/nipoppy/blob/main/workflow/proc_pipe/mriqc/Dockerfile)

See [md_check_link log](https://github.com/neurobagel/documentation/actions/runs/6240533464/job/16940832217#step:4:78)

**Comment by surchs** [comment]
Let's address this to unblock #83

**Comment by rmanaem** [comment]
Hi @michellewang could you take a look and see if this is a quick fix?
